version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_FRONT_PORT}:80"
      - "${NGINX_SERVER_PORT}:3000"
    depends_on:
      - php
      - node
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/server:/var/www/server
    environment:
      - TZ=${TZ}
    container_name: wdr_niginx_local
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www/server
    tty: true
    depends_on:
      - mysql
    volumes:
      - ./src/server:/var/www/server
    container_name: wdr_php_local
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    working_dir: /var/www/front
    tty: true
    ports:
      - "${NODE_SERVER_PORT}:3000"
    volumes:
      - ./src/front:/var/www/front
    container_name: wdr_node_local
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    container_name: wdr_mysql_local
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    container_name: wdr_phpmyadmin_local
  mailhog_local:
    image: mailhog/mailhog
    ports:
      - "${MAILHOG_PORT}:8025"
    container_name: wdr_mailhog_local

volumes:
  mysql-data:
    external: false
